export const asiaData = [
  {
    name: "Afghanistan",
    capital: "Kabul",
    formationYear: 1919,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Afghanistan is dated to 1919. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Afghanistan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Afghanistan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Kabul, and the institutions created during the country's most recent constitutional or independence period. Today Afghanistan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Armenia",
    capital: "Yerevan",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Armenia is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "Armenia developed from ancient and medieval societies whose institutions, trade networks, languages, and belief systems shaped the political culture of the region. Its historical landscape was influenced by ancient armenian kingdoms, persian/russian rule, soviet, and modern armenia.\n\nOver time, Armenia was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Yerevan, and the institutions created during the country's most recent constitutional or independence period. Today Armenia is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Azerbaijan is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "Azerbaijan developed from ancient and medieval societies whose institutions, trade networks, languages, and belief systems shaped the political culture of the region. Its historical landscape was influenced by persian, turkic, russian, and soviet.\n\nOver time, Azerbaijan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Baku, and the institutions created during the country's most recent constitutional or independence period. Today Azerbaijan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Bahrain",
    capital: "Manama",
    formationYear: 1971,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Bahrain is dated to 1971. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Bahrain has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Bahrain was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Manama, and the institutions created during the country's most recent constitutional or independence period. Today Bahrain is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Bangladesh",
    capital: "Dhaka",
    formationYear: 1971,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Bangladesh is dated to 1971. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Bangladesh has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Bangladesh was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Dhaka, and the institutions created during the country's most recent constitutional or independence period. Today Bangladesh is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Bhutan",
    capital: "Thimphu",
    formationYear: 1910,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Bhutan is dated to 1910. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Bhutan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Bhutan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Thimphu, and the institutions created during the country's most recent constitutional or independence period. Today Bhutan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    formationYear: 1984,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Brunei is dated to 1984. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Brunei has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Brunei was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Bandar Seri Begawan, and the institutions created during the country's most recent constitutional or independence period. Today Brunei is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Cambodia",
    capital: "Phnom Penh",
    formationYear: 1953,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Cambodia is dated to 1953. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Cambodia has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Cambodia was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Phnom Penh, and the institutions created during the country's most recent constitutional or independence period. Today Cambodia is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "China",
    capital: "Beijing",
    formationYear: "1949",
    independenceInfo: "Modern China was established as the People's Republic of China on 1 October 1949 after the Chinese Communist Party won the Chinese Civil War on the mainland. The People's Republic became the government controlling most of the territory of present-day China.",
    historicalOverview: "China's history reaches back thousands of years, with early states developing along the Yellow and Yangtze rivers and a succession of dynasties building political institutions, writing traditions, and major infrastructure. The Qin unified much of the historical Chinese heartland in 221 BCE, while the Han, Tang, Song, Ming, and other dynasties expanded and reshaped the country over subsequent centuries.\n\nThe nineteenth and early twentieth centuries brought major disruption. Foreign intervention, unequal treaties, internal rebellions, the fall of the Qing dynasty in 1911, and the rivalry between Nationalists and Communists transformed Chinese politics. The Second Sino-Japanese War and the wider Second World War caused enormous destruction and further altered the balance between the competing Chinese movements.\n\nThe People's Republic was proclaimed in 1949, while the Republic of China government continued on Taiwan. Since 1949, the mainland has experienced rapid industrialization, major economic reforms beginning in the late 1970s, and a transformation into one of the world's largest economies. Modern China combines an ancient cultural inheritance with a highly urbanized and technologically advanced society."
  },
  {
    name: "Cyprus",
    capital: "Nicosia",
    formationYear: 1960,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Cyprus is dated to 1960. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Cyprus has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Cyprus was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Nicosia, and the institutions created during the country's most recent constitutional or independence period. Today Cyprus is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Georgia",
    capital: "Tbilisi",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Georgia is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "Georgia developed from ancient and medieval societies whose institutions, trade networks, languages, and belief systems shaped the political culture of the region. Its historical landscape was influenced by caucasian, persian, ottoman, russian, and soviet.\n\nOver time, Georgia was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Tbilisi, and the institutions created during the country's most recent constitutional or independence period. Today Georgia is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "India",
    capital: "New Delhi",
    formationYear: "1947",
    independenceInfo: "India became independent from British rule on 15 August 1947, ending nearly two centuries of expanding British political control. Independence created the sovereign Dominion of India, which became a republic in 1950.",
    historicalOverview: "India's civilization has roots in the Indus Valley cities, followed by the rise of Vedic cultures, regional kingdoms, the Mauryan and Gupta empires, and many later states across the subcontinent. Trade, religion, literature, and science developed through long interactions among diverse communities, while Buddhism, Hindu traditions, Jainism, Islam, Sikhism, and other traditions became deeply connected to the region's history.\n\nFrom the medieval period onward, large political formations such as the Delhi Sultanate and Mughal Empire governed extensive territories, while numerous regional kingdoms retained their own institutions. European trading powers arrived by sea, and the British East India Company gradually expanded its political authority before the British Crown took direct control after the uprising of 1857. Nationalist movements then grew across the subcontinent.\n\nIndia achieved independence in 1947 amid the partition of British India into India and Pakistan, a traumatic transition accompanied by mass displacement and communal violence. The Constitution came into force on 26 January 1950, establishing the Republic of India. Since then, India has developed as a federal democratic republic with a large and diverse population, a growing economy, and a major role in regional and global affairs."
  },
  {
    name: "Indonesia",
    capital: "Jakarta",
    formationYear: "1945",
    independenceInfo: "Indonesia proclaimed independence from Dutch colonial rule on 17 August 1945. Dutch recognition of Indonesian sovereignty followed the Indonesian National Revolution in 1949.",
    historicalOverview: "The Indonesian archipelago has a long history of maritime trade linking South and Southeast Asia. Early Hindu-Buddhist states such as Srivijaya and Majapahit developed extensive networks, while later Muslim sultanates became influential across many islands. Local societies remained diverse, with hundreds of languages and traditions shaped by trade and migration.\n\nEuropean powers entered the region during the age of maritime expansion, and the Dutch East India Company established a strong commercial and political presence. The Dutch colonial state gradually expanded control over much of the archipelago, although resistance continued in various regions. Japanese occupation during the Second World War weakened Dutch authority and encouraged Indonesian nationalist mobilization.\n\nLeaders Sukarno and Mohammad Hatta proclaimed independence in 1945, beginning a difficult struggle against the returning Dutch. Sovereignty was recognized in 1949, after which Indonesia built a unified republican state spanning thousands of islands. The modern country has experienced periods of parliamentary government, centralized rule, democratic reform, and rapid economic change, while continuing to manage extraordinary cultural and geographic diversity."
  },
  {
    name: "Iran",
    capital: "Tehran",
    formationYear: 1501,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Iran is dated to 1501. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "Iran developed from ancient and medieval societies whose institutions, trade networks, languages, and belief systems shaped the political culture of the region. Its historical landscape was influenced by elamite, persian empires, safavid, qajar, and modern iran.\n\nOver time, Iran was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Tehran, and the institutions created during the country's most recent constitutional or independence period. Today Iran is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Iraq",
    capital: "Baghdad",
    formationYear: 1932,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Iraq is dated to 1932. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Iraq has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Iraq was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Baghdad, and the institutions created during the country's most recent constitutional or independence period. Today Iraq is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Israel",
    capital: "Jerusalem",
    formationYear: 1948,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Israel is dated to 1948. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Israel has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Israel was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Jerusalem, and the institutions created during the country's most recent constitutional or independence period. Today Israel is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Japan",
    capital: "Tokyo",
    formationYear: "660 BCE",
    independenceInfo: "Japan is a sovereign state with an ancient political tradition, while 660 BCE is the traditional accession date of Emperor Jimmu rather than a documented modern founding date. Japan's modern constitutional state emerged through the Meiji transformation and later postwar reforms.",
    historicalOverview: "Japan's early history includes Jomon hunter-gatherer communities, Yayoi agriculture, and the emergence of centralized political authority associated with the Yamato court. Over the centuries, Japanese institutions were influenced by contacts with Korea and China, while distinctive forms of literature, religion, architecture, and court culture developed within the archipelago.\n\nFrom the late twelfth century, warrior governments dominated national politics, producing centuries of shogunal rule and regional rivalry. The Tokugawa shogunate reunified the country in the early seventeenth century and maintained a long period of internal stability. In 1868, the Meiji Restoration redirected Japan toward rapid centralization, industrialization, military modernization, and a new constitutional order.\n\nJapan's expansion in Asia contributed to wars with China and Russia and ultimately to its role in the Second World War. After Japan's defeat in 1945, the country adopted a new constitution in 1947 and rebuilt its political and economic institutions. The postwar decades brought remarkable economic growth, while modern Japan became known for advanced manufacturing, technology, cultural influence, and a constitutional monarchy with parliamentary government."
  },
  {
    name: "Jordan",
    capital: "Amman",
    formationYear: 1946,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Jordan is dated to 1946. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Jordan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Jordan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Amman, and the institutions created during the country's most recent constitutional or independence period. Today Jordan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Kazakhstan",
    capital: "Astana",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Kazakhstan is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Kazakhstan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Kazakhstan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Astana, and the institutions created during the country's most recent constitutional or independence period. Today Kazakhstan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Kuwait",
    capital: "Kuwait City",
    formationYear: 1961,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Kuwait is dated to 1961. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Kuwait has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Kuwait was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Kuwait City, and the institutions created during the country's most recent constitutional or independence period. Today Kuwait is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Kyrgyzstan",
    capital: "Bishkek",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Kyrgyzstan is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Kyrgyzstan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Kyrgyzstan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Bishkek, and the institutions created during the country's most recent constitutional or independence period. Today Kyrgyzstan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Laos",
    capital: "Vientiane",
    formationYear: 1953,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Laos is dated to 1953. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Laos has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Laos was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Vientiane, and the institutions created during the country's most recent constitutional or independence period. Today Laos is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Lebanon",
    capital: "Beirut",
    formationYear: 1943,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Lebanon is dated to 1943. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Lebanon has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Lebanon was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Beirut, and the institutions created during the country's most recent constitutional or independence period. Today Lebanon is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Malaysia",
    capital: "Kuala Lumpur",
    formationYear: 1957,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Malaysia is dated to 1957. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Malaysia has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Malaysia was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Kuala Lumpur, and the institutions created during the country's most recent constitutional or independence period. Today Malaysia is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Maldives",
    capital: "Malé",
    formationYear: 1965,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Maldives is dated to 1965. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Maldives has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Maldives was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Malé, and the institutions created during the country's most recent constitutional or independence period. Today Maldives is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Mongolia",
    capital: "Ulan Bator",
    formationYear: 1990,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Mongolia is dated to 1990. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "Mongolia developed from ancient and medieval societies whose institutions, trade networks, languages, and belief systems shaped the political culture of the region. Its historical landscape was influenced by steppe confederations, mongol empire, qing, and modern mongolian.\n\nOver time, Mongolia was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Ulan Bator, and the institutions created during the country's most recent constitutional or independence period. Today Mongolia is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Myanmar",
    capital: "Naypyidaw",
    formationYear: 1948,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Myanmar is dated to 1948. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Myanmar has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Myanmar was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Naypyidaw, and the institutions created during the country's most recent constitutional or independence period. Today Myanmar is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Nepal",
    capital: "Kathmandu",
    formationYear: 2008,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Nepal is dated to 2008. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Nepal has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Nepal was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Kathmandu, and the institutions created during the country's most recent constitutional or independence period. Today Nepal is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "North Korea",
    capital: "Pyongyang",
    formationYear: 1948,
    independenceInfo: "The modern formation or independence milestone most commonly associated with North Korea is dated to 1948. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern North Korea has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, North Korea was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Pyongyang, and the institutions created during the country's most recent constitutional or independence period. Today North Korea is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Oman",
    capital: "Muscat",
    formationYear: 1744,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Oman is dated to 1744. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Oman has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Oman was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Muscat, and the institutions created during the country's most recent constitutional or independence period. Today Oman is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Pakistan",
    capital: "Islamabad",
    formationYear: 1947,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Pakistan is dated to 1947. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Pakistan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Pakistan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Islamabad, and the institutions created during the country's most recent constitutional or independence period. Today Pakistan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Palestine",
    capital: "Ramallah",
    formationYear: "1988",
    independenceInfo: "Palestine has an ancient state tradition, while the modern political system developed through several historical stages. The year shown in WorldLore represents a traditional or commonly used formation milestone rather than a single moment when the country's full modern boundaries appeared.",
    historicalOverview: "The territory of modern Palestine has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Palestine was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Ramallah, and the institutions created during the country's most recent constitutional or independence period. Today Palestine is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Philippines",
    capital: "Manila",
    formationYear: 1946,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Philippines is dated to 1946. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Philippines has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Philippines was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Manila, and the institutions created during the country's most recent constitutional or independence period. Today Philippines is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Qatar",
    capital: "Doha",
    formationYear: 1971,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Qatar is dated to 1971. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Qatar has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Qatar was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Doha, and the institutions created during the country's most recent constitutional or independence period. Today Qatar is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Saudi Arabia",
    capital: "Riyadh",
    formationYear: "1932",
    independenceInfo: "The modern Kingdom of Saudi Arabia was unified by Abdulaziz Ibn Saud, who proclaimed the kingdom on 23 September 1932. The new state brought much of the Arabian Peninsula's central and western territories under one monarchy.",
    historicalOverview: "Arabia has been inhabited and connected through trade for thousands of years, with routes linking the Mediterranean, East Africa, and South Asia. The rise of Islam in the seventh century transformed the peninsula and the wider world, while Mecca and Medina became central religious destinations. Later centuries saw the emergence of regional emirates, tribal alliances, and shifting imperial influence.\n\nIn the eighteenth century, an alliance between Muhammad ibn Abd al-Wahhab and Muhammad ibn Saud helped establish a political-religious movement that influenced the central Arabian region. The first and second Saudi states were defeated, but the Saudi family remained politically active. Abdulaziz recaptured Riyadh in 1902 and spent decades consolidating territories before unification.\n\nThe 1938 discovery of commercial oil transformed Saudi Arabia's economic prospects and accelerated state development. The kingdom invested heavily in infrastructure, education, healthcare, and energy production, while retaining its absolute monarchy. Modern Saudi Arabia remains one of the world's major energy producers and a central state in Middle Eastern diplomacy and Islamic affairs."
  },
  {
    name: "Singapore",
    capital: "Singapore",
    formationYear: 1965,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Singapore is dated to 1965. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Singapore has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Singapore was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Singapore, and the institutions created during the country's most recent constitutional or independence period. Today Singapore is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "South Korea",
    capital: "Seoul",
    formationYear: "1948",
    independenceInfo: "The Republic of Korea was established on 15 August 1948 in the southern part of the Korean Peninsula after the end of Japanese colonial rule. It developed as a separate Korean state alongside the Democratic People's Republic of Korea in the north.",
    historicalOverview: "Korean history extends back to ancient polities such as Gojoseon and later kingdoms including Goguryeo, Baekje, and Silla. Silla unified much of the peninsula in the seventh century, followed by the Goryeo and Joseon dynasties. Korean political institutions, Confucian scholarship, literature, and distinctive cultural traditions developed over many centuries.\n\nJapan formally annexed Korea in 1910 and ruled the peninsula until its defeat in 1945. Liberation was followed by division at the 38th parallel and increasing rivalry between the Soviet- and US-backed zones. The Korean War began in 1950 and caused immense destruction before an armistice in 1953 left the peninsula divided.\n\nSouth Korea then underwent authoritarian rule, rapid industrialization, and major social change. Democratic reforms in the late twentieth century established a more competitive political system. Today the Republic of Korea is a highly urbanized, technologically advanced democracy with a major global role in manufacturing, entertainment, science, and international trade."
  },
  {
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    formationYear: 1948,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Sri Lanka is dated to 1948. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Sri Lanka has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Sri Lanka was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Sri Jayawardenepura Kotte, and the institutions created during the country's most recent constitutional or independence period. Today Sri Lanka is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Syria",
    capital: "Damascus",
    formationYear: 1946,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Syria is dated to 1946. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Syria has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Syria was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Damascus, and the institutions created during the country's most recent constitutional or independence period. Today Syria is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Tajikistan",
    capital: "Dushanbe",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Tajikistan is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Tajikistan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Tajikistan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Dushanbe, and the institutions created during the country's most recent constitutional or independence period. Today Tajikistan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Thailand",
    capital: "Bangkok",
    formationYear: 1238,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Thailand is dated to 1238. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "Thailand developed from ancient and medieval societies whose institutions, trade networks, languages, and belief systems shaped the political culture of the region. Its historical landscape was influenced by sukhothai, ayutthaya, and chakri.\n\nOver time, Thailand was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Bangkok, and the institutions created during the country's most recent constitutional or independence period. Today Thailand is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Timor-Leste",
    capital: "Dili",
    formationYear: 2002,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Timor-Leste is dated to 2002. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Timor-Leste has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Timor-Leste was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Dili, and the institutions created during the country's most recent constitutional or independence period. Today Timor-Leste is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Turkey",
    capital: "Ankara",
    formationYear: "1923",
    independenceInfo: "The Republic of Turkey was proclaimed on 29 October 1923 after the Turkish War of Independence and the collapse of the Ottoman imperial order. Mustafa Kemal Ataturk became the republic's founding leader and first president.",
    historicalOverview: "Anatolia has been home to ancient civilizations including the Hittites, Greeks, Persians, and Romans, and it later became a central region of the Byzantine Empire. Turkic migration and settlement increased after the eleventh-century Seljuk victories, creating new political and cultural patterns in Anatolia. In 1453, the Ottoman conquest of Constantinople established a new imperial center.\n\nThe Ottoman Empire expanded across southeastern Europe, the Middle East, and North Africa, reaching its height in the early modern period. By the nineteenth century, military defeats, nationalist movements, and administrative reforms challenged the empire. The First World War brought further losses, and the postwar partition proposals triggered the Turkish national movement led by Mustafa Kemal.\n\nThe nationalist victory led to the abolition of the sultanate, the Treaty of Lausanne, and the establishment of the Republic of Turkey in 1923. Ataturk's government introduced sweeping legal, educational, and cultural reforms, including a secular republican framework. Modern Turkey has continued to evolve through periods of political change, economic development, and debates over the relationship between secularism, democracy, national identity, and religion."
  },
  {
    name: "Turkmenistan",
    capital: "Ashgabat",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Turkmenistan is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Turkmenistan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Turkmenistan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Ashgabat, and the institutions created during the country's most recent constitutional or independence period. Today Turkmenistan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    formationYear: 1971,
    independenceInfo: "The modern formation or independence milestone most commonly associated with United Arab Emirates is dated to 1971. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern United Arab Emirates has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, United Arab Emirates was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Abu Dhabi, and the institutions created during the country's most recent constitutional or independence period. Today United Arab Emirates is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Uzbekistan",
    capital: "Tashkent",
    formationYear: 1991,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Uzbekistan is dated to 1991. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Uzbekistan has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Uzbekistan was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Tashkent, and the institutions created during the country's most recent constitutional or independence period. Today Uzbekistan is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Vietnam",
    capital: "Hanoi",
    formationYear: 1945,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Vietnam is dated to 1945. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Vietnam has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Vietnam was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Hanoi, and the institutions created during the country's most recent constitutional or independence period. Today Vietnam is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Yemen",
    capital: "Sanaa",
    formationYear: 1990,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Yemen is dated to 1990. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Yemen has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Yemen was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Sanaa, and the institutions created during the country's most recent constitutional or independence period. Today Yemen is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Russia",
    capital: "Moscow",
    formationYear: 862,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Russia is dated to 862. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "Russia developed from ancient and medieval societies whose institutions, trade networks, languages, and belief systems shaped the political culture of the region. Its historical landscape was influenced by kievan rus, muscovy, russian empire, and soviet.\n\nOver time, Russia was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected asia, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Moscow, and the institutions created during the country's most recent constitutional or independence period. Today Russia is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Egypt",
    capital: "Cairo",
    formationYear: "1922",
    independenceInfo: "Egypt received formal independence from British protection on 28 February 1922, although British influence remained significant for decades. The monarchy was later overthrown in the 1952 revolution, and the republic was established in 1953.",
    historicalOverview: "Ancient Egypt developed along the Nile more than five thousand years ago and became one of the world's most enduring civilizations. Dynastic states built monumental architecture, complex religious traditions, systems of writing, and centralized administration. Egypt was later ruled by Persian, Greek, Roman, and Byzantine powers before the Arab conquest in the seventh century.\n\nIslamic Egypt became a major center of trade and learning, especially under the Fatimid, Ayyubid, and Mamluk periods. The Ottoman Empire conquered Egypt in 1517, and Muhammad Ali's dynasty later built a powerful semi-autonomous state. British influence expanded during the nineteenth century, culminating in occupation in 1882.\n\nFormal independence in 1922 established a constitutional monarchy, but foreign influence and domestic political conflict continued. The Free Officers' Revolution of 1952 ended the monarchy, and Gamal Abdel Nasser reshaped the state around republican nationalism and state-led development. Modern Egypt remains a major Arab and African country whose history is closely tied to the Nile, the Suez Canal, and its position between Africa and the Middle East."
  }
];
