export const northAmericaData = [
  {
    name: "Antigua and Barbuda",
    capital: "Saint John's",
    formationYear: 1981,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Antigua and Barbuda is dated to 1981. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Antigua and Barbuda has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Antigua and Barbuda was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Saint John's, and the institutions created during the country's most recent constitutional or independence period. Today Antigua and Barbuda is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Bahamas",
    capital: "—",
    formationYear: 1973,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Bahamas is dated to 1973. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Bahamas has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Bahamas was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, —, and the institutions created during the country's most recent constitutional or independence period. Today Bahamas is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Barbados",
    capital: "Bridgetown",
    formationYear: 1966,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Barbados is dated to 1966. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Barbados has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Barbados was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Bridgetown, and the institutions created during the country's most recent constitutional or independence period. Today Barbados is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Belize",
    capital: "Belmopan",
    formationYear: 1981,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Belize is dated to 1981. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Belize has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Belize was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Belmopan, and the institutions created during the country's most recent constitutional or independence period. Today Belize is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Canada",
    capital: "Ottawa",
    formationYear: "1867",
    independenceInfo: "Canada became a self-governing dominion through Confederation on 1 July 1867, uniting Ontario, Quebec, Nova Scotia, and New Brunswick. Constitutional independence developed gradually, culminating in the Constitution Act of 1982.",
    historicalOverview: "Indigenous peoples have lived across the lands of present-day Canada for thousands of years, maintaining diverse nations, languages, and traditions. French and British colonization created competing imperial settlements, especially around the St. Lawrence River and Atlantic coast. The Seven Years' War transferred most French North American possessions to Britain, while Quebec retained a distinctive French-speaking society.\n\nPolitical tensions in British North America encouraged Confederation in 1867, and additional provinces and territories later joined the federation. Canada expanded westward through treaties, settlement, and railway construction, often at immense cost to Indigenous communities. The country gradually gained control over more of its foreign and domestic affairs while remaining constitutionally linked to Britain.\n\nThe Statute of Westminster in 1931 gave Canada broad legislative autonomy, and the Constitution Act of 1982 patriated the constitution and added the Canadian Charter of Rights and Freedoms. Modern Canada is a federal parliamentary constitutional monarchy with both English- and French-speaking traditions. Its contemporary identity also increasingly emphasizes Indigenous rights, multiculturalism, and a large, diverse immigrant population."
  },
  {
    name: "Costa Rica",
    capital: "San Jose",
    formationYear: "1821",
    independenceInfo: "Costa Rica declared independence from Spain on 15 September 1821 as part of Central America's broader independence movement. It later became a separate republic after the dissolution of the Central American federation.",
    historicalOverview: "Before Spanish colonization, the territory was home to diverse Indigenous peoples whose societies developed trade networks and agricultural traditions. Spain established colonial settlements in the sixteenth century, although the region remained less densely populated and less economically central than several neighboring areas. Local communities developed a strong tradition of small-scale agriculture.\n\nAfter independence in 1821, Costa Rica joined the United Provinces of Central America before becoming fully sovereign. Coffee cultivation became a major source of wealth during the nineteenth century and contributed to the development of political institutions. The country experienced political competition and occasional instability but avoided some of the large-scale wars that affected its neighbors.\n\nCosta Rica abolished its military in 1948 after a brief civil conflict, making civilian government and social investment central to the country's modern identity. It developed strong institutions in education, health, and environmental protection. Today Costa Rica is a stable democratic republic known for biodiversity conservation, tourism, and a long tradition of constitutional government."
  },
  {
    name: "Cuba",
    capital: "Havana",
    formationYear: "1902",
    independenceInfo: "Cuba became an independent republic on 20 May 1902 after the Spanish-American War and a period of US administration. Formal sovereignty was therefore established in the early twentieth century, although the United States retained significant influence for decades.",
    historicalOverview: "Cuba was inhabited by Indigenous peoples before Spanish colonization began in the early sixteenth century. Havana grew into a major Spanish Caribbean port, and the island's economy became heavily dependent on sugar and the labor of enslaved Africans. Spanish rule produced a complex society linking Caribbean, European, and African traditions.\n\nCuban independence movements emerged in the nineteenth century, including the Ten Years' War and the final war begun in 1895 under leaders such as Jose Marti. The Spanish-American War in 1898 ended Spanish rule, after which the United States administered the island for several years. Independence followed in 1902 under a new republican constitution.\n\nPolitical instability and foreign influence continued during the early republic. The Cuban Revolution led by Fidel Castro overthrew the government of Fulgencio Batista in 1959 and established a socialist state aligned with the Soviet Union. Modern Cuba remains a one-party socialist republic with a distinctive political system, internationally important cultural traditions, and a history deeply shaped by its relationship with the United States."
  },
  {
    name: "Dominica",
    capital: "Roseau",
    formationYear: 1978,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Dominica is dated to 1978. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Dominica has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Dominica was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Roseau, and the institutions created during the country's most recent constitutional or independence period. Today Dominica is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Dominican Republic",
    capital: "Santo Domingo",
    formationYear: 1844,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Dominican Republic is dated to 1844. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Dominican Republic has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Dominican Republic was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Santo Domingo, and the institutions created during the country's most recent constitutional or independence period. Today Dominican Republic is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "El Salvador",
    capital: "San Salvador",
    formationYear: 1841,
    independenceInfo: "The modern formation or independence milestone most commonly associated with El Salvador is dated to 1841. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern El Salvador has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, El Salvador was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, San Salvador, and the institutions created during the country's most recent constitutional or independence period. Today El Salvador is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Grenada",
    capital: "St. George's",
    formationYear: 1974,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Grenada is dated to 1974. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Grenada has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Grenada was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, St. George's, and the institutions created during the country's most recent constitutional or independence period. Today Grenada is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Guatemala",
    capital: "Guatemala City",
    formationYear: "1821",
    independenceInfo: "Guatemala became independent from Spain on 15 September 1821 as part of the independence of Central America. It later became an independent republic after the collapse of the United Provinces of Central America.",
    historicalOverview: "Guatemala contains the heartland of major Maya civilizations, including powerful urban centers such as Tikal and other cities connected through trade, religion, and political rivalry. Spanish forces conquered the region in the sixteenth century, creating the Captaincy General of Guatemala within the Spanish Empire. Colonial society relied on Indigenous labor and hierarchical institutions.\n\nCentral American independence was proclaimed in 1821, followed by a short-lived political union among several former Spanish provinces. Guatemala experienced repeated struggles over federalism, central authority, land ownership, and relations between Indigenous and elite communities. Nineteenth-century governments sought to restructure the economy around export agriculture, especially coffee.\n\nThe twentieth century included dictatorship, reformist experiments, a civil war from 1960 to 1996, and the long process of democratic reconstruction. The 1996 peace accords ended the armed conflict and introduced broad political commitments. Modern Guatemala is a constitutional republic with a large Indigenous population, a diverse cultural heritage, and continuing challenges involving inequality, governance, and development."
  },
  {
    name: "Haiti",
    capital: "Port-au-Prince",
    formationYear: 1804,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Haiti is dated to 1804. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Haiti has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Haiti was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Port-au-Prince, and the institutions created during the country's most recent constitutional or independence period. Today Haiti is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Honduras",
    capital: "Tegucigalpa",
    formationYear: 1838,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Honduras is dated to 1838. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Honduras has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Honduras was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Tegucigalpa, and the institutions created during the country's most recent constitutional or independence period. Today Honduras is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Jamaica",
    capital: "Kingston",
    formationYear: 1962,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Jamaica is dated to 1962. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Jamaica has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Jamaica was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Kingston, and the institutions created during the country's most recent constitutional or independence period. Today Jamaica is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Mexico",
    capital: "Mexico City",
    formationYear: "1821",
    independenceInfo: "Mexico achieved independence from Spanish rule on 27 September 1821 after a prolonged war that began in 1810. The new country inherited a monarchy before becoming a federal republic.",
    historicalOverview: "Mexico's history includes major Mesoamerican civilizations such as the Olmec, Maya, Teotihuacan, and Mexica. Spanish forces under Hernan Cortes conquered the Mexica capital Tenochtitlan in 1521, and Spain built the vast colony of New Spain. Indigenous, European, and African peoples became connected through colonial society, labor systems, religion, and trade.\n\nIndependence movements began with Miguel Hidalgo's call in 1810 and continued through years of warfare. The conflict eventually brought together former opponents under the Plan of Iguala, leading to independence in 1821. The nineteenth century was marked by political instability, territorial losses, civil conflict, and the Reform period, followed by the long rule of Porfirio Diaz.\n\nThe Mexican Revolution began in 1910 and led to major political and social reforms. The Constitution of 1917 remains a foundational document of the modern state. Mexico developed a strong federal government, diversified economy, and major cultural influence across the Spanish-speaking world, while continuing to address inequality, regional differences, and questions of governance."
  },
  {
    name: "Nicaragua",
    capital: "Managua",
    formationYear: 1838,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Nicaragua is dated to 1838. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Nicaragua has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Nicaragua was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Managua, and the institutions created during the country's most recent constitutional or independence period. Today Nicaragua is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Panama",
    capital: "Panama City",
    formationYear: "1903",
    independenceInfo: "Panama separated from Colombia on 3 November 1903 and established an independent republic. The new government soon entered an agreement with the United States that enabled construction and later operation of the Panama Canal.",
    historicalOverview: "Panama's isthmus has long connected Caribbean and Pacific worlds and supported Indigenous communities and regional trade. Spanish colonization began in the early sixteenth century, and Panama became an important route for moving wealth across the isthmus between the Atlantic and Pacific. After independence from Spain in 1821, Panama joined Colombia and later became part of larger Colombian political arrangements.\n\nThe nineteenth century saw repeated political changes in Colombia and growing international interest in a canal across Panama. A French canal attempt in the 1880s failed, but the strategic importance of the route remained. Separation from Colombia in 1903 created the modern Panamanian republic, whose early years were closely tied to the United States and the Canal Zone.\n\nThe Panama Canal opened in 1914 and reshaped global shipping. US control of the canal and surrounding zone remained a major political issue until the Torrijos-Carter treaties transferred full control to Panama in 1999. Modern Panama is a sovereign presidential republic and a major logistics and financial hub linking the Atlantic and Pacific."
  },
  {
    name: "Saint Kitts and Nevis",
    capital: "Basseterre",
    formationYear: 1983,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Saint Kitts and Nevis is dated to 1983. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Saint Kitts and Nevis has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Saint Kitts and Nevis was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Basseterre, and the institutions created during the country's most recent constitutional or independence period. Today Saint Kitts and Nevis is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Saint Lucia",
    capital: "Castries",
    formationYear: 1979,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Saint Lucia is dated to 1979. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Saint Lucia has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Saint Lucia was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Castries, and the institutions created during the country's most recent constitutional or independence period. Today Saint Lucia is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    formationYear: 1979,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Saint Vincent and the Grenadines is dated to 1979. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Saint Vincent and the Grenadines has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Saint Vincent and the Grenadines was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Kingstown, and the institutions created during the country's most recent constitutional or independence period. Today Saint Vincent and the Grenadines is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    formationYear: 1962,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Trinidad and Tobago is dated to 1962. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Trinidad and Tobago has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Trinidad and Tobago was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected north america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Port of Spain, and the institutions created during the country's most recent constitutional or independence period. Today Trinidad and Tobago is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "United States",
    capital: "Washington, D.C.",
    formationYear: "1776",
    independenceInfo: "The United States declared independence from Great Britain on 4 July 1776. The Constitution later established the federal government in 1787 and took effect in 1789.",
    historicalOverview: "Indigenous peoples inhabited North America for thousands of years before European colonization. British, French, Spanish, Dutch, and other settlements developed across different regions, while the thirteen British colonies along the Atlantic coast became increasingly tied to imperial markets and institutions. Indigenous nations retained their own governments and territories, though colonial expansion brought conflict and displacement.\n\nDisputes over taxation, representation, and imperial authority produced the American Revolution. The Declaration of Independence announced a new political principle centered on popular sovereignty, followed by a long war that ended with British recognition of American independence in 1783. The Constitution then created a federal republic with separated powers.\n\nThe new country expanded rapidly across the continent, but expansion was accompanied by slavery, war, and the dispossession of Indigenous peoples. The Civil War from 1861 to 1865 ended legal slavery in the United States and preserved the Union, while industrialization transformed the economy. Today the United States is a federal constitutional republic with major global influence in science, technology, culture, and international affairs."
  }
];
