export const southAmericaData = [
  {
    name: "Argentina",
    capital: "Buenos Aires",
    formationYear: "1816",
    independenceInfo: "Argentina formally declared independence from Spain on 9 July 1816 at the Congress of Tucuman. The country later developed a federal republic after prolonged conflicts over regional and central power.",
    historicalOverview: "Indigenous societies occupied the territory of present-day Argentina before Spanish settlement. Spain established Buenos Aires and incorporated the region into the Viceroyalty of the Rio de la Plata in the late eighteenth century. The area became an important Atlantic trading center connected to broader imperial commerce.\n\nThe May Revolution of 1810 weakened Spanish rule in Buenos Aires and began the political process that eventually produced independence. Military campaigns and regional conflicts continued for years, and the Congress of Tucuman declared independence in 1816. The nineteenth century was dominated by struggles between federalists and centralists and by the gradual consolidation of a national government.\n\nLarge-scale European immigration, agricultural exports, railway construction, and urban growth transformed Argentina in the late nineteenth and early twentieth centuries. Political instability, military coups, and economic crises continued through much of the twentieth century. Modern Argentina is a federal presidential republic with a strong cultural identity, major agricultural production, and a prominent role in South American affairs."
  },
  {
    name: "Bolivia",
    capital: "Sucre",
    formationYear: "1825",
    independenceInfo: "Bolivia declared independence from Spain on 6 August 1825 after a long struggle involving regional revolutionaries and the campaigns of Simon Bolivar and Antonio Jose de Sucre. The new republic was named in honor of Bolivar.",
    historicalOverview: "Bolivia's highlands were home to civilizations including Tiwanaku, while the wider region later became part of the Inca Empire. Spanish conquest incorporated the area into the colonial system, with Potosi becoming one of the world's great silver-mining centers. Colonial labor systems had profound effects on Indigenous communities and regional society.\n\nIndependence struggles began with uprisings in the late eighteenth and early nineteenth centuries and continued through years of war. Royalist forces remained strong in Upper Peru, but the collapse of Spanish power and the arrival of Sucre's forces opened the way for independence. The republic was established in 1825, with Sucre as its first constitutional leader.\n\nBolivia experienced repeated political upheaval, territorial losses, and economic dependence on mineral exports. The twentieth century included the 1952 National Revolution, military governments, democratic transitions, and major debates over Indigenous rights and natural resources. Modern Bolivia is a plurinational republic with a population deeply shaped by Indigenous cultures and a strategic economy built around gas, minerals, and agriculture."
  },
  {
    name: "Brazil",
    capital: "Brasilia",
    formationYear: "1822",
    independenceInfo: "Brazil declared independence from Portugal on 7 September 1822 under Pedro, who later became Emperor Pedro I. The country became a republic in 1889.",
    historicalOverview: "Brazil's history begins with diverse Indigenous peoples who inhabited the Amazon, coast, cerrado, and other regions long before European arrival. Portuguese explorers reached the coast in 1500, and Portugal gradually established settlements centered on sugar, mining, and Atlantic trade. The colony became one of the largest destinations in the transatlantic slave trade.\n\nIn 1808, the Portuguese royal court moved to Rio de Janeiro during the Napoleonic Wars, transforming Brazil's political status and institutions. When the court later returned to Lisbon, Pedro remained in Brazil and declared independence in 1822. The Brazilian Empire then expanded and consolidated the territory while continuing to rely heavily on slavery until abolition in 1888.\n\nA military coup ended the monarchy in 1889 and created the Brazilian Republic. The twentieth century brought industrialization, authoritarian governments, democratic periods, and major social changes. Modern Brazil is a federal presidential republic, the largest country in South America, and a major global economy with extraordinary linguistic, cultural, and ecological diversity."
  },
  {
    name: "Chile",
    capital: "Santiago",
    formationYear: "1818",
    independenceInfo: "Chile declared independence from Spain in 1818 after several years of war. Bernardo O'Higgins became one of the leading figures of the independence movement.",
    historicalOverview: "Chile's long precolonial history includes Mapuche and other Indigenous societies, while the Inca Empire controlled parts of the north before Spanish conquest. Pedro de Valdivia established Santiago in 1541, and Chile became a frontier region of the Spanish Empire. The Mapuche maintained long resistance to Spanish expansion in the south.\n\nThe independence movement began with the 1810 creation of a local governing junta. After an initial period of conflict, Spanish forces temporarily restored control, but Chilean patriots returned to the struggle with support from Jose de San Martin and forces crossing the Andes. Victory at the Battle of Maipu in 1818 secured the new republic.\n\nChile expanded economically through mining, agriculture, and Pacific trade, and the War of the Pacific in the late nineteenth century changed its northern borders. The twentieth century included periods of democratic government, military rule under Augusto Pinochet, and a return to democracy beginning in 1990. Modern Chile is a presidential republic with strong institutions and a highly developed export-oriented economy."
  },
  {
    name: "Colombia",
    capital: "Bogota",
    formationYear: "1810",
    independenceInfo: "Colombia's independence movement began with the 20 July 1810 uprising in Bogota, while decisive military victories led to independence from Spain in 1819. The modern republic emerged through several constitutional reorganizations.",
    historicalOverview: "Pre-Columbian Colombia was home to diverse societies, including the Muisca, Tairona, and other communities with sophisticated agriculture, trade, and craftsmanship. Spain established the Viceroyalty of New Granada, and colonial cities such as Bogota became political and religious centers. Gold and other resources connected the region to the wider Spanish empire.\n\nPolitical crisis in Spain during the Napoleonic era triggered local juntas and independence movements in Spanish America. Simon Bolivar's campaigns helped defeat Spanish forces and establish Gran Colombia, a federation that briefly united territories across northern South America. Political disagreements later broke the federation apart.\n\nColombia continued to experience constitutional change, regional conflict, and civil wars during the nineteenth and twentieth centuries. A long internal armed conflict involved guerrilla groups, paramilitaries, and the state, while later peace negotiations reduced the role of some armed organizations. Modern Colombia is a presidential republic with a diversified economy, major cities, and a growing regional and international presence."
  },
  {
    name: "Ecuador",
    capital: "Quito",
    formationYear: 1822,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Ecuador is dated to 1822. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Ecuador has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Ecuador was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected south america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Quito, and the institutions created during the country's most recent constitutional or independence period. Today Ecuador is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Guyana",
    capital: "Georgetown",
    formationYear: 1966,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Guyana is dated to 1966. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Guyana has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Guyana was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected south america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Georgetown, and the institutions created during the country's most recent constitutional or independence period. Today Guyana is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Paraguay",
    capital: "Asunción",
    formationYear: 1811,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Paraguay is dated to 1811. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Paraguay has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Paraguay was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected south america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Asunción, and the institutions created during the country's most recent constitutional or independence period. Today Paraguay is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Peru",
    capital: "Lima",
    formationYear: "1821",
    independenceInfo: "Peru declared independence from Spain on 28 July 1821, although Spanish forces remained active for several years. The final defeat of royalist armies came in 1824 after the campaigns of Jose de San Martin and Simon Bolivar.",
    historicalOverview: "Peru contains the heartlands of ancient Andean civilizations, including the Norte Chico tradition and later the Inca Empire. Spanish forces captured the Inca ruler Atahualpa in 1532, and the conquest produced a colonial society centered on Lima. Silver mining and forced labor systems became central to the Spanish imperial economy.\n\nThe colonial period lasted nearly three centuries and connected Peru to Atlantic and Pacific trade networks. Independence movements gained strength in the early nineteenth century, and Jose de San Martin entered Lima in 1821 to proclaim independence. Spanish forces were ultimately defeated in the campaigns of Bolivar and Antonio Jose de Sucre, with the Battle of Ayacucho in 1824 proving decisive.\n\nThe new republic faced military coups, regional rivalries, and major economic cycles based on mining and exports. The twentieth century brought reform, authoritarian rule, terrorism, and democratic reconstruction. Modern Peru is a presidential republic with a rich Indigenous, Spanish, African, and Asian cultural heritage and a diversified economy linked strongly to mining and agriculture."
  },
  {
    name: "Suriname",
    capital: "Paramaribo",
    formationYear: 1975,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Suriname is dated to 1975. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Suriname has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Suriname was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected south america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Paramaribo, and the institutions created during the country's most recent constitutional or independence period. Today Suriname is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Uruguay",
    capital: "Montevideo",
    formationYear: 1828,
    independenceInfo: "The modern formation or independence milestone most commonly associated with Uruguay is dated to 1828. Earlier states, kingdoms, empires, or constitutional arrangements also contributed to the country's present political identity.",
    historicalOverview: "The territory of modern Uruguay has a much older history than its present political boundaries. Communities developed through agriculture, trade, migration, local kingdoms, and interaction with neighboring regions, creating cultural traditions that still influence the country today.\n\nOver time, Uruguay was reshaped by changing states, external powers, economic systems, and political movements. The modern country emerged through a combination of local state-building and the wider forces that affected south america, including imperial expansion, nationalism, constitutional change, or decolonization where relevant.\n\nThe modern state developed around its capital, Montevideo, and the institutions created during the country's most recent constitutional or independence period. Today Uruguay is a distinct sovereign state with a historical identity built from older regional traditions as well as modern political structures, and its society continues to reflect the long process by which the present country took shape."
  },
  {
    name: "Venezuela",
    capital: "Caracas",
    formationYear: "1811",
    independenceInfo: "Venezuela declared independence from Spain on 5 July 1811, although the war continued for years and independence was only secured after further campaigns. The territory later became part of Gran Colombia before becoming a separate republic in 1830.",
    historicalOverview: "Venezuela was home to diverse Indigenous societies before Spanish colonization. Spain established coastal settlements and colonial institutions, while agriculture, cattle ranching, and trade became major parts of the economy. Caracas emerged as a political center within the Captaincy General of Venezuela.\n\nRevolutionary movements began in the early nineteenth century, with Francisco de Miranda and later Simon Bolivar becoming central figures. Spanish forces defeated early revolutionary governments, but Bolivar's campaigns eventually helped secure independence across northern South America. Venezuela joined Gran Colombia before separating in 1830.\n\nThe discovery of large petroleum reserves transformed Venezuela during the twentieth century and made oil the dominant source of state revenue. The country experienced military rule, democratic governments, social programs, and eventually severe political and economic crisis. Modern Venezuela remains a federal presidential republic with enormous energy resources and a complex contemporary political landscape."
  }
];
